### ISSUE TITLE
Souci de Genre

### ISSUE THREAD

**Issue by julienXX** [julienXX/learnhaskell#11]
Il faudrait qu'on essaie d'utiliser des termes inclusifs (par rapport au genre) au maximum, c'est facile en anglais beaucoup moins en français.

**Comment by rolios** [comment]
Un exemple ?

**Comment by berewt** [comment]
Le vouvoiement marche bien pour éviter ces soucis, non ?

**Comment by julienXX** [comment]
Developpeur par exemple

**Comment by berewt** [comment]
On peut tenter de neutraliser ça autant que possible mais si rien ne vient, ne pas bloquer dessus. Surtout sur la première version.
