### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by julienXX** [julienXX/learnhaskell#3]

**Comment by julienXX** [comment]
Je suis moyennant convaincu par ma traduction de "Well, actually". Si vous avez des suggestions.

**Comment by julienXX** [comment]
Aussi guidelines traduit en Lignes directrices je sais pas si c'est le mieux.

**Comment by berewt** [comment]
Recommandations me semble mieux pour guidelines.

Y'a quelques passages qui pourrait être reformulé dans un français plus idiomatique mais rien de choquant. Soit on fait une première passe complète, soit je fais les propositions maintenant, comme vous préférez.

**Comment by julienXX** [comment]
Autant essayer de faire une première passe complète et on affine ensuite, ca me semble plus efficace mais comme vous le sentez.

**Comment by julienXX** [comment]
@berewt @OlivierGonthier je vous ai ajouté comme collaborateurs au repo, ce sera surement plus simple à gérer.
